### ISSUE TITLE
运行项目后一直在报错

### ISSUE THREAD

**Issue by jeunggaaising** [l526614169/uni-zjw-template#1]
页面一直在loading，请问一下是不是要修改某些配置才可以运行
![image](https://user-images.githubusercontent.com/88656652/225268122-0a492163-386c-4def-a613-f1af285a010a.png)
****

**Comment by ShadowSmallBaby** [comment]
不是有资源不存在报404了,然后运行环境是什么

**Comment by jeunggaaising** [comment]
运行环境是node 10.7.0
我查看network发现是mgop在报错
![image](https://user-images.githubusercontent.com/88656652/225273042-e1984920-2630-412e-af86-d8eb98d606d5.png)

![image](https://user-images.githubusercontent.com/88656652/225272811-1ddd85a6-e377-49a7-8631-5ffc6db5fa18.png)

![image](https://user-images.githubusercontent.com/88656652/225273244-554d37be-5d65-4089-97fe-36793e31286f.png)

**Comment by ShadowSmallBaby** [comment]
可以的话去博客给我私信,详细了解,看看是什么问题

**Comment by jeunggaaising** [comment]
请问一下博客的入口地址是？



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 徐小宝 ***@***.***&gt;
发送时间: 2023年3月16日 08:40
收件人: l526614169/uni-zjw-template ***@***.***&gt;
抄送: Jeunggaaising ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [l526614169/uni-zjw-template] 运行项目后一直在报错 (Issue #1)





 
可以的话去博客给我私信,详细了解,看看是什么问题

**Comment by ShadowSmallBaby** [comment]
我的主页挂了一个CSDN的地址

**Comment by jeunggaaising** [comment]
感谢感谢！



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 徐小宝 ***@***.***&gt;
发送时间: 2023年3月16日 08:56
收件人: l526614169/uni-zjw-template ***@***.***&gt;
抄送: Jeunggaaising ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [l526614169/uni-zjw-template] 运行项目后一直在报错 (Issue #1)





 
我的主页挂了一个CSDN的地址
